# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fias.fields.address


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fias', '0005_load_stats_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('location', fias.fields.address.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fias.AddrObj')),
            ],
        ),
        migrations.CreateModel(
            name='ItemWithArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('area', fias.fields.address.ChainedAreaField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fias.AddrObj')),
                ('location', fias.fields.address.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fias.AddrObj')),
            ],
        ),
    ]
