# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fias.fields.free


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0015_auto_20161224_0054'),
        ('tst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeAddressItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('location', fias.fields.free.FreeAddressField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.AddrObj')),
            ],
        ),
    ]
