# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrobj',
            name='cadnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addrobj',
            name='divtype',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='house',
            name='cadnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='divtype',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='house',
            name='regioncode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='landmark',
            name='cadnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
