# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0003_actstat_centerst_curentst_eststat_hststat_intvstat_ndoctype_operstat_strstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normdoc',
            options={'verbose_name': 'Нормативный документ', 'verbose_name_plural': 'Нормативные документы'},
        ),
        migrations.AlterModelOptions(
            name='socrbase',
            options={'ordering': ['level', 'scname'], 'verbose_name': 'Тип адресного объекта', 'verbose_name_plural': 'Типы адресных объектов'},
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='docdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='docimgid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор образа (внешний ключ)'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='docname',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование документа'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='docnum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='doctype',
            field=models.PositiveIntegerField(verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='normdocid',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='Идентификатор нормативного документа'),
        ),
        migrations.AlterField(
            model_name='socrbase',
            name='item_weight',
            field=models.PositiveSmallIntegerField(default=64, help_text='Используется для сортировки результатов поиска с помощью Sphinx. Допустимые значения 1-128. Чем больше число, тем выше объекты данного типа в поиске.', verbose_name='Вес типа объекта'),
        ),
        migrations.AlterField(
            model_name='socrbase',
            name='kod_t_st',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Ключевое поле'),
        ),
        migrations.AlterField(
            model_name='socrbase',
            name='level',
            field=models.PositiveSmallIntegerField(verbose_name='Уровень адресного объекта'),
        ),
        migrations.AlterField(
            model_name='socrbase',
            name='scname',
            field=models.CharField(default=' ', max_length=10, verbose_name='Краткое наименование типа объекта'),
        ),
        migrations.AlterField(
            model_name='socrbase',
            name='socrname',
            field=models.CharField(default=' ', max_length=50, verbose_name='Полное наименование типа объекта'),
        ),
    ]
