# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0005_load_stats_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrobj',
            name='operstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.OperStat'),
        ),
        migrations.AlterField(
            model_name='addrobj',
            name='centstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.CenterSt'),
        ),
        migrations.AlterField(
            model_name='addrobj',
            name='currstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.CurentSt'),
        ),
    ]
