# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0006_add_fks_to_addrobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='eststatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.EstStat'),
        ),
        migrations.AlterField(
            model_name='house',
            name='strstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.StrStat'),
        ),
    ]
