# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0007_add_fks_to_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseint',
            name='intstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.IntvStat'),
        ),
    ]
