# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0010_room_stead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrobj',
            name='centstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.CenterSt'),
        ),
        migrations.AlterField(
            model_name='addrobj',
            name='currstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.CurentSt'),
        ),
        migrations.AlterField(
            model_name='addrobj',
            name='operstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.OperStat'),
        ),
        migrations.AlterField(
            model_name='house',
            name='eststatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.EstStat'),
        ),
        migrations.AlterField(
            model_name='house',
            name='strstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.StrStat'),
        ),
        migrations.AlterField(
            model_name='houseint',
            name='intstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.IntvStat'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='doctype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.NDocType', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='room',
            name='operstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.OperStat'),
        ),
        migrations.AlterField(
            model_name='stead',
            name='operstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fias.OperStat'),
        ),
    ]
