# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0012_field_descriptions_and_more_fks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addrobj',
            options={'ordering': ['aolevel', 'formalname'], 'verbose_name': 'Адресообразующий элемент', 'verbose_name_plural': 'Адресообразующие элементы'},
        ),
        migrations.AlterModelOptions(
            name='houseint',
            options={'verbose_name': 'Интервал домов', 'verbose_name_plural': 'Интервалы домов'},
        ),
        migrations.AlterModelOptions(
            name='landmark',
            options={'verbose_name': 'Место расположения имущественного объекта', 'verbose_name_plural': 'Места расположения имущественных объектов'},
        ),
    ]
