# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0015_auto_20161224_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='stead',
            name='counter',
            field=models.IntegerField(null=True),
        ),
    ]
