# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0017_flattype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flattype',
            name='id',
        ),
        migrations.AlterField(
            model_name='flattype',
            name='fltypeid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0442\u0438\u043f\u0430 \u043f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f \u0438\u043b\u0438 \u043e\u0444\u0438\u0441\u0430'),
        ),
    ]
