# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0018_auto_20181008_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0442\u0438\u043f\u0430')),
                ('shortname', models.CharField(max_length=255, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0442\u0438\u043f\u0430')),
                ('rmtypeid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0442\u0438\u043f\u0430 \u043a\u043e\u043c\u043d\u0430\u0442\u044b')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043a\u043e\u043c\u043d\u0430\u0442\u044b',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043a\u043e\u043c\u043d\u0430\u0442',
            },
        ),
    ]
